server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /
    session:
      timeout: #
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/springdb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
mybatis:
    mapper-locations: classpath:mybatis/*Mapper.xml
    type-aliases-package: com.sunny.managementsystem.entity